### ISSUE TITLE
how to install it on windows  10 computer

### ISSUE THREAD

**Issue by Sandy4321** [chuanconggao/PrefixSpan-py#13]
Only it is not clear how to install it on windows  10 computer
and how to use for supervising learning
for example for train data with only 2 classes at last token in the sequence
"yes" and "no"

**Comment by chuanconggao** [comment]
Hi, for applications like supervised learning, please refer to a good survey paper from Jiawei Han. Sorry, I do not remember the exact title any more. You can search with keyword "jiawei han survey" on dblp.org.

Personally I do not use Windows, so there is no personal instruction from me. However, this package does not have any platform-specific logic, and should work out-of-box. Please search online on how to install Python package on Windows.
