### ISSUE TITLE
import error: SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by weitang730** [chuanconggao/PrefixSpan-py#19]
Hi,
I have installed prefixspan 0.5.2 and want to import it in Jupyter Notebook.

import prefixspan

Traceback (most recent call last):

  File "E:\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2961, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-4-8d816d998e5a>", line 6, in <module>
    import prefixspan

  File "E:\anaconda3\lib\site-packages\prefixspan\__init__.py", line 5, in <module>
    from .frequent import PrefixSpan_frequent

  File "E:\anaconda3\lib\site-packages\prefixspan\frequent.py", line 5, in <module>
    from extratools.dicttools import nextentries

  File "E:\anaconda3\lib\site-packages\extratools\dicttools.py", line 30
    r: Mapping[VT, List[KT]] = defaultdict(list)
     ^
SyntaxError: invalid syntax

Could you help me take a look then?

Thanks,
Wei

**Comment by nltran** [comment]
You need to install ```extratools``` as well.

**Comment by tlarock** [comment]
I am having the same problem after installing `prefixspan` through `pip` on Anaconda python 3.5.3. `extratools` is installed, hence the error on a specific line in `extratools/dicttools.py`. Tried uninstalling and reinstalling through `pip`, no change.

It seems like maybe my interpreter is not buying this use of `typing`? Is there a specific way to install, or is an older/newer version necessary? Again, tried uninstalling and reinstalling `typing` through `pip` to no change.

**Comment by VBota1** [comment]
I had the same problem on python 3.5.x changed to 3.6.x and the issue was gone.

There is also a note at the end of the README: 

> Note that only the earlier version 0.4 works for the latest PyPy3 6.0.0 (compatible with Python 3.5.3). Please install it via pip3 install prefixspan==0.4. Latest version should work for the future PyPy3 (compatible with Python 3.6).

**Comment by chuanconggao** [comment]
Closing as already resolved.
