### ISSUE TITLE
Returning matching pattern indices 

### ISSUE THREAD

**Issue by agalea91** [chuanconggao/PrefixSpan-py#21]
When I run `topk`, I get out a list of patterns and their frequencies. e.g.

```
[[66741, ['/home', '/home']],
 [42351, ['/home', '/basket.html']],
 [41275, ['/home', '/signin.html']]]
```

I would like to use these as features, so I need to map them back to their indices in the training data. This data is available in the callback/key/filter functions e.g. `key=lambda patt, matches` (I want `matches`).

Is there a way to return this match data? Should I use a callback function to store it?

**Comment by agalea91** [comment]
Here's the callback function I've been using to accomplish this:

```python
def callback(patt, matches, top_k, patt_indices):
    patt_id = '_'.join([str(x) for x in patt])
    patt_indices[patt_id] = [m[0] for m in matches]
    top_k.append([len(matches), patt])

db = [
    [0, 1, 2, 3, 4],
    [1, 1, 1, 3, 4],
    [2, 1, 2, 2, 0],
    [1, 1, 1, 2, 2],
]
top_k = []
patt_indices = {}
prefix_spans = PrefixSpan(db)
prefix_spans.topk(k, callback=lambda patt, matches: callback(patt, matches, top_k, patt_indices))
```

**Comment by chuanconggao** [comment]
Closing as already supported.
