### ISSUE TITLE
The output I get looks very weird to me

### ISSUE THREAD

**Issue by johann-petrak** [chuanconggao/PrefixSpan-py#23]
Trying prefixspan-0.5.2 with python 3.6.8

I am running `prefixspan-cli frequent 5 --closed ids.txt  > seqs.ids` 

ids.txt:  https://gist.github.com/johann-petrak/9d07e3bacd167639c26defb822dbe6aa 
seqs.ids: https://gist.github.com/johann-petrak/7db1b94153816075556798db1d068069

If you look at the line 4 from the bottom, this is "34 1 0 2 : 6" and the next line is 
"34 0 2 : 8". 

If you look at the input you will notice that "34 0 2" does not occur anywhere in the input, so why is it included in the output with frequency 8?

**Comment by VBota1** [comment]
So I looked over the input you indicated and I found 8 instances of the pattern "34 0 2" :

line 65:     **34** 1 **0 2** 8
line 67:     **34** 1 **0 2** 9
line 69:     **34** 1 **0 2** 3
line 164:   **34** 1 **0 2** 8
line 168:   4 **34** 1 **0 2** 9
line 174:   4 **34** 25 **0** 35 **2** 3 32 2 8
line 305:   **34** 1 **0 2** 8
line 473:   **34** 71 **0 2** 3 72 0 25 2 3 27 61

I also found the 6 instances for pattern "34 1 0 2"

**Comment by LoLei** [comment]
Yes, I was initially also confused by this, in any sequential pattern mining algorithm, that the definition of a subsequence works with gaps.

So as @VBota1 said, `34 0 2` is a subsequence of e.g. `34 1 0 2 8`, even though it does not appear literally in it, the elements occur in the right order, given gaps with interspersed other items.

**Comment by chuanconggao** [comment]
Close as it seems already answered. Thanks for explanation. 

Please also recheck as I just merged a fix for closed algorithm #14. Thanks.

**Comment by johann-petrak** [comment]
My expectation would have been that unless the size and number of gaps are specified, no gaps would be allowed. In many situations one just wants proper subsequences without gaps, in other situations e.g. subsequences with at most 1 gap of at most 2 elements etc. 
But this algorithm does not seem to have a command line option to control this and I did also not see a mention about what the default settings are. 

But clearly id does not make much sense in many applications to allow any number of gaps of any size.

**Comment by LoLei** [comment]
@johann-petrak I suggest you read this survey about sequential pattern mining [[Fournier-Viger et al., 2017](http://www.philippe-fournier-viger.com/dspr-paper5.pdf)]. The introduction describes what sequential patterns are in general, and why gap constraints are not universally needed, and there are also short descriptions of the various algorithms and their parameters.

Also the papers of PrefixSpan [[Pei et al., 2004](http://www.philippe-fournier-viger.com/spmf/prefixspan.pdf)], BIDE [[Wang et al., 2007](http://www.philippe-fournier-viger.com/spmf/icde04_bide.pdf)] and FEAT [[Gao et al., 2008](http://www.philippe-fournier-viger.com/spmf/FEAT_2008.pdf)] are of course interesting.

This repository merely provides efficient implementations of these algorithms.

Adding gap constraints arbitrarily to an existing algorithm is not trivial, as the possibility heavily depends on how that specific algorithm works. For some, gap-constraint versions have been proposed after the original algorithm was published, e.g. Gap-BIDE [[Li and Wang, 2008](https://doi.org/10.1137/1.9781611972788.28)].
