### ISSUE TITLE
Does not work properly with text

### ISSUE THREAD

**Issue by vedantg12** [chuanconggao/PrefixSpan-py#26]
The given code does not work properly with text.
Example:
input I gave was,
What is your name?
What is the main theme of the party?
.....
The output had a lot of problems.
Can I use your code with sentences?

**Comment by DNXie** [comment]
Same here. 

My data:
~~~python
I am Bob
good morning
good evening
hello everyone
hello everybody
~~~

Running `prefixspan-cli frequent 1 --text --closed test.dat`

gives me 
~~~python
hello everybody : 5
hello everybody Bob : 1
~~~

**Comment by chuanconggao** [comment]
For text mode, please double check on starting and trailing spaces. Be aware that symbol is treated as part of word. 

If still have issue, please attach exact text. Thanks.
