### ISSUE TITLE
How to get the prefixspan-cli working?

### ISSUE THREAD

**Issue by hmanso02** [chuanconggao/PrefixSpan-py#4]
I tried to install setup.py using "python setup.py" but it throws an error. How do I use the prefixspan-cli option? It keeps throwing an error for me. I am particularly interested in using the maxlen option in my python code. How do I use maxlen in python code rather than using it on the terminal? Would greatly appreciate any help!

**Comment by chuanconggao** [comment]
You need to install using `pip3 install prefixspan`. `setup.py` is used to package the library for publishing on PyPI.

**Comment by hmanso02** [comment]
thanks so much for the quick response. Just wanted a quick follow up. Can I use the 'maxlen' option in python code or do I need to use it on the terminal? I tried to use it in my python code earlier but it threw an error. would greatly appreciate an example. thanks!

**Comment by chuanconggao** [comment]
You can use it in your code. The CLI is just a wrapper of the library. Everything that the CLI does can be established in your code. Please refer to the source code of CLI for more details.
