### ISSUE TITLE
Incorrect frequent patterns

### ISSUE THREAD

**Issue by imanly97** [chuanconggao/PrefixSpan-py#42]
I'm getting patterns that have the wrong frequency counts. I assuming there should be no gaps when generating these FP's and no double counting. I've asterisked a few that I believe to be incorrect. 

input:

sequences = 
[0, 1, 0, 0, 0]
[1, 0, 0, 0, 1]
[0, 1, 0, 0, 1]
[0, 0, 1, 0, 1]
[1, 0, 0, 0, 0]
[1, 0, 0, 0, 0]
[1, 0, 0, 1, 0]
[0, 0, 0, 0, 0]
[0, 1, 0, 0, 0]
[0, 0, 0, 0, 0]
[1, 0, 0, 1, 1]
[0, 1, 1, 0, 0]
[0, 1, 0, 0, 1]
[1, 0, 0, 0, 1]
[1, 1, 1, 1, 0]

output:

from prefixspan import PrefixSpan
prefix_span = PrefixSpan(sequences)

min_support = 7
frequent_patterns = prefix_span.frequent(min_support, closed=True)

for pattern in frequent_patterns:
    print(pattern)

(15, [0])
(10, [0, 1])
(7, [0, 1, 0])
(14, [0, 0])
(13, [0, 0, 0]) *
(7, [0, 0, 1])
(13, [1])
(13, [1, 0])
(11, [1, 0, 0]) 
(7, [1, 0, 0, 0]) *
(7, [1, 0, 1]) *
(9, [1, 1]) *

**Comment by chuanconggao** [comment]
Please read the original paper. Pattern can include gap. Both with * are correct.

**Comment by imanly97** [comment]
Thanks
