### ISSUE TITLE
generator returns error

### ISSUE THREAD

**Issue by AllerLydia** [chuanconggao/PrefixSpan-py#8]
TypeError: 'int' object is not subscriptable 

using API example code.

**Comment by chuanconggao** [comment]
I am sorry but I am not sure which example your are referring to. Please give more specific details.

**Comment by AllerLydia** [comment]
from prefixspan import PrefixSpan

db = [
    [0, 1, 2, 3, 4],
    [1, 1, 1, 3, 4],
    [2, 1, 2, 2, 0],
    [1, 1, 1, 2, 2],
]

ps = PrefixSpan(db)

print(ps.topk(5, generator=True))

using Ipython notebook.

**Comment by chuanconggao** [comment]
Thanks. I will take a look.

**Comment by chuanconggao** [comment]
Issue in upstream dependence extratools. Will fix soon. Thank you for reporting.

**Comment by chuanconggao** [comment]
Updated extratools to 0.8.1 and bumped PrefixSpan-py to 0.5.2. The issue should be fixed. Please update your local versions.

Thank you. Please let me know if there is any further issue.
